//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageBeheersTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StageBeheersTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin/einde stageperiode semester 1.
        /// </summary>
        public static string DisplayBeginEindeSemester1 {
            get {
                return ResourceManager.GetString("DisplayBeginEindeSemester1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin/einde stageperiode semester 2.
        /// </summary>
        public static string DisplayBeginEindeSemester2 {
            get {
                return ResourceManager.GetString("DisplayBeginEindeSemester2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Semester 1.
        /// </summary>
        public static string DisplayBeginSem1 {
            get {
                return ResourceManager.GetString("DisplayBeginSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Semester2.
        /// </summary>
        public static string DisplayBeginSem2 {
            get {
                return ResourceManager.GetString("DisplayBeginSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline voor bedrijven om stageopdrachten te wijzigen.
        /// </summary>
        public static string DisplayDeadlineBedrijfMagStageWijzigen {
            get {
                return ResourceManager.GetString("DisplayDeadlineBedrijfMagStageWijzigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einde Semester 1.
        /// </summary>
        public static string DisplayEindeSem1 {
            get {
                return ResourceManager.GetString("DisplayEindeSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einde Semester 2.
        /// </summary>
        public static string DisplayEindeSem2 {
            get {
                return ResourceManager.GetString("DisplayEindeSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord.
        /// </summary>
        public static string DisplayNewPassword {
            get {
                return ResourceManager.GetString("DisplayNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord bevestigen.
        /// </summary>
        public static string DisplayNieuwWachtwoordBevestigen {
            get {
                return ResourceManager.GetString("DisplayNieuwWachtwoordBevestigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidig wachtwoord.
        /// </summary>
        public static string DisplayOldPassword {
            get {
                return ResourceManager.GetString("DisplayOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string DisplayWachtwoord {
            get {
                return ResourceManager.GetString("DisplayWachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het aanmaken van een account voor &apos;{0}&apos; is mislukt. Het account bestaat mogelijk al..
        /// </summary>
        public static string ErrorAanmakenAccount {
            get {
                return ResourceManager.GetString("ErrorAanmakenAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academiejaar mag niet tot het verleden behoren.
        /// </summary>
        public static string ErrorAcademiejaarInVerleden {
            get {
                return ResourceManager.GetString("ErrorAcademiejaarInVerleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het veld bedrijf is verplicht..
        /// </summary>
        public static string ErrorBedrijfVerplicht {
            get {
                return ResourceManager.GetString("ErrorBedrijfVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleider aanmaken mislukt: Er bestaat al een begeleider met hogent E-mail &apos;{0}&apos;..
        /// </summary>
        public static string ErrorBegeleiderCreateHogentEmailBestaatAl {
            get {
                return ResourceManager.GetString("ErrorBegeleiderCreateHogentEmailBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De begindatum moet na de einddatum liggen.
        /// </summary>
        public static string ErrorBegindatumNaEinddatum {
            get {
                return ResourceManager.GetString("ErrorBegindatumNaEinddatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het aanmaken van een account voor &apos;{0}&apos; is mislukt. Het account bestaat mogelijk al..
        /// </summary>
        public static string ErrorCreateAccount {
            get {
                return ResourceManager.GetString("ErrorCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrijf aanmaken mislukt. Er bestaat al een bedrijf met de E-mail &apos;{0}&apos;..
        /// </summary>
        public static string ErrorCreateBedrijf {
            get {
                return ResourceManager.GetString("ErrorCreateBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &apos;{0}&apos; verwijderen mislukt..
        /// </summary>
        public static string ErrorDeleteAccount {
            get {
                return ResourceManager.GetString("ErrorDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen mislukt. Bedrijf heeft 1 of meerdere ingediende stageopdrachten..
        /// </summary>
        public static string ErrorDeleteBedrijf {
            get {
                return ResourceManager.GetString("ErrorDeleteBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen mislukt. Stagebegeleider is aan 1 of meerdere stages koppeld..
        /// </summary>
        public static string ErrorDeleteBegeleider {
            get {
                return ResourceManager.GetString("ErrorDeleteBegeleider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht verwijderen mislukt: De stageopdracht &apos;{0}&apos; is gekoppeld aan 1 of meerdere studenten/stagebegeleider/....
        /// </summary>
        public static string ErrorDeleteStageopdracht {
            get {
                return ResourceManager.GetString("ErrorDeleteStageopdracht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student verwijderen mislukt. De student &apos;{0}&apos; is koppeld aan 1 of meerdere stages..
        /// </summary>
        public static string ErrorDeleteStudent {
            get {
                return ResourceManager.GetString("ErrorDeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen kolom geselecteerd..
        /// </summary>
        public static string ErrorExcelGeenKolommen {
            get {
                return ResourceManager.GetString("ErrorExcelGeenKolommen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen standaardstageperiodes gevonden voor dit academiejaar. Gelieve deze eerst in te stellen alvorens stageopdrachten aan studenten toe te wijzen..
        /// </summary>
        public static string ErrorGeenStageperiodesIngesteld {
            get {
                return ResourceManager.GetString("ErrorGeenStageperiodesIngesteld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail verzenden mislukt. Het bedrijf &apos;{0}&apos; heeft geen geldig E-mailadres ({1})..
        /// </summary>
        public static string ErrorMailBedrijf {
            get {
                return ResourceManager.GetString("ErrorMailBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het nieuwe wachtwoord en het bevestigde antwoord komen niet overeen..
        /// </summary>
        public static string ErrorNieuwEnBevestigdWachtwoord {
            get {
                return ResourceManager.GetString("ErrorNieuwEnBevestigdWachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig Academiejaar formaat. beginjaar-eindjaar.
        /// </summary>
        public static string ErrorOngeldigAcademiejaarFormaat {
            get {
                return ResourceManager.GetString("ErrorOngeldigAcademiejaarFormaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige afbeelding grootte, max. {0} Kb..
        /// </summary>
        public static string ErrorOngeldigeAfbeeldingGrootte {
            get {
                return ResourceManager.GetString("ErrorOngeldigeAfbeeldingGrootte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het ingevoerde e-mailadres of wachtwoord is onjuist..
        /// </summary>
        public static string ErrorOngeldigeLoginPoging {
            get {
                return ResourceManager.GetString("ErrorOngeldigeLoginPoging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig semester: Semester mag enkel de waarde 1 of 2 hebben..
        /// </summary>
        public static string ErrorOngeldigSemester {
            get {
                return ResourceManager.GetString("ErrorOngeldigSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verplicht oud wachtwoord in te vullen..
        /// </summary>
        public static string ErrorOudWachtwoordVerplicht {
            get {
                return ResourceManager.GetString("ErrorOudWachtwoordVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageperiode mag niet leeg zijn bij aangepaste een stageperiode..
        /// </summary>
        public static string ErrorSetStageperiode {
            get {
                return ResourceManager.GetString("ErrorSetStageperiode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage toewijzen aan student mislukt. Stagedossier moet eerst goedgekeurd worden..
        /// </summary>
        public static string ErrorStageAanStudentKoppelenZonderGoedgekeurdStagedossier {
            get {
                return ResourceManager.GetString("ErrorStageAanStudentKoppelenZonderGoedgekeurdStagedossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleiding aanvraag goedkeuren mislukt: Stage &apos;{0}&apos; heeft al een stagebegeleider({1}).
        /// </summary>
        public static string ErrorStagebegeleidingAanvraagGoedkeuren {
            get {
                return ResourceManager.GetString("ErrorStagebegeleidingAanvraagGoedkeuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is al een stagedossier aangeduid als ingediend.
        /// </summary>
        public static string ErrorStagedossierReedsIngediend {
            get {
                return ResourceManager.GetString("ErrorStagedossierReedsIngediend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student moet stageopdracht als voorkeur aangeduid hebben alvorens een stagedossier als ingediend aan te kunnen duiden..
        /// </summary>
        public static string ErrorStagedossierStageopdrachtNietAlsVoorkeur {
            get {
                return ResourceManager.GetString("ErrorStagedossierStageopdrachtNietAlsVoorkeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De stageopdracht is niet meer beschikbaar..
        /// </summary>
        public static string ErrorStageNietMeerBeschikbaar {
            get {
                return ResourceManager.GetString("ErrorStageNietMeerBeschikbaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht afkeuren mislukt. De stageopdracht is al toegewezen..
        /// </summary>
        public static string ErrorStageopdrachtAfkeuren {
            get {
                return ResourceManager.GetString("ErrorStageopdrachtAfkeuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foute stageperiode voor semester 1: begindatum moet na de einddatum liggen.
        /// </summary>
        public static string ErrorStageperiodeSem1 {
            get {
                return ResourceManager.GetString("ErrorStageperiodeSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foute stageperiode voor semester 2: begindatum moet na de einddatum liggen.
        /// </summary>
        public static string ErrorStageperiodeSem2 {
            get {
                return ResourceManager.GetString("ErrorStageperiodeSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student aanmaken mislukt: Er bestaat al een student met hogent E-mail &apos;{0}&apos;..
        /// </summary>
        public static string ErrorStudentCreateHogentEmailBestaatAl {
            get {
                return ResourceManager.GetString("ErrorStudentCreateHogentEmailBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student heeft al een toegewezen stage.
        /// </summary>
        public static string ErrorStudentHeeftAlToegewezenStage {
            get {
                return ResourceManager.GetString("ErrorStudentHeeftAlToegewezenStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mag niet langer zijn dan {1} characters..
        /// </summary>
        public static string ErrorVeldlengte {
            get {
                return ResourceManager.GetString("ErrorVeldlengte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verplicht begindatum en einddatum in te geven bij een aangepaste stageperiode..
        /// </summary>
        public static string ErrorVerplichtBeginEnEindDatum {
            get {
                return ResourceManager.GetString("ErrorVerplichtBeginEnEindDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goegekeurde stages kunnen niet meer verwijderd worden..
        /// </summary>
        public static string ErrorVerwijderGoedgekeurdeStage {
            get {
                return ResourceManager.GetString("ErrorVerwijderGoedgekeurdeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht &apos;{0}&apos; staat al bij mijn voorkeurstages..
        /// </summary>
        public static string ErrorVoorkeurStageToevoegen {
            get {
                return ResourceManager.GetString("ErrorVoorkeurStageToevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorkeurstage verwijderen mislukt. Stagedossier voor deze stage is aangeduid als ingediend..
        /// </summary>
        public static string ErrorVoorkeurStageVerwijderen {
            get {
                return ResourceManager.GetString("ErrorVoorkeurStageVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorkeurstage verwijderen mislukt. Opgegeven voorkeurstage niet bij mijn voorkeurstages gevonden..
        /// </summary>
        public static string ErrorVoorkeurVerwijderenNietGevonden {
            get {
                return ResourceManager.GetString("ErrorVoorkeurVerwijderenNietGevonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link om wachtwoord te resetten is naar uw e-mail verzonden..
        /// </summary>
        public static string InfoResetWachtwoordVerzonden {
            get {
                return ResourceManager.GetString("InfoResetWachtwoordVerzonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &apos;{0}&apos; succesvol aangemaakt..
        /// </summary>
        public static string SuccesAanmakenAccount {
            get {
                return ResourceManager.GetString("SuccesAanmakenAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens succesvol opgeslagen..
        /// </summary>
        public static string SuccesAdminsGewijzigd {
            get {
                return ResourceManager.GetString("SuccesAdminsGewijzigd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin {0} succesvol verwijderd..
        /// </summary>
        public static string SuccesAdminVerwijderd {
            get {
                return ResourceManager.GetString("SuccesAdminVerwijderd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleider {0} toegevoegd..
        /// </summary>
        public static string SuccesBegeleiderCreate {
            get {
                return ResourceManager.GetString("SuccesBegeleiderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord gewijzigd..
        /// </summary>
        public static string SuccesChangePassword {
            get {
                return ResourceManager.GetString("SuccesChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrijf &apos;{0}&apos; succesvol aangemaakt..
        /// </summary>
        public static string SuccesCreateBedrijf {
            get {
                return ResourceManager.GetString("SuccesCreateBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactpersoon &apos;{0}&apos; aangemaakt..
        /// </summary>
        public static string SuccesCreateContactpersoon {
            get {
                return ResourceManager.GetString("SuccesCreateContactpersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht succesvol aangemaakt..
        /// </summary>
        public static string SuccesCreateStageopdracht {
            get {
                return ResourceManager.GetString("SuccesCreateStageopdracht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account van &apos;{0}&apos; succesvol verwijderd..
        /// </summary>
        public static string SuccesDeleteAccount {
            get {
                return ResourceManager.GetString("SuccesDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagebedrijf &apos;{0}&apos; werd succesvol verwijderd..
        /// </summary>
        public static string SuccesDeleteBedrijf {
            get {
                return ResourceManager.GetString("SuccesDeleteBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleider &apos;{0}&apos; werd succesvol verwijderd..
        /// </summary>
        public static string SuccesDeleteBegeleider {
            get {
                return ResourceManager.GetString("SuccesDeleteBegeleider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactpersoon &apos;{0}&apos; succesvol verwijderd..
        /// </summary>
        public static string SuccesDeleteContactpersoon {
            get {
                return ResourceManager.GetString("SuccesDeleteContactpersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage verwijderd..
        /// </summary>
        public static string SuccesDeleteStage {
            get {
                return ResourceManager.GetString("SuccesDeleteStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student &apos;{0}&apos; werd succesvol verwijderd..
        /// </summary>
        public static string SuccesDeleteStudent {
            get {
                return ResourceManager.GetString("SuccesDeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &apos;{0}&apos; succesvol gewijzigd..
        /// </summary>
        public static string SuccesEditAccount {
            get {
                return ResourceManager.GetString("SuccesEditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens gewijzigd..
        /// </summary>
        public static string SuccesEditBedrijf {
            get {
                return ResourceManager.GetString("SuccesEditBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigingen succesvol opgeslagen..
        /// </summary>
        public static string SuccesEditSaved {
            get {
                return ResourceManager.GetString("SuccesEditSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage wijzigingen opgeslagen..
        /// </summary>
        public static string SuccesEditStage {
            get {
                return ResourceManager.GetString("SuccesEditStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registratie e-mail verzonden..
        /// </summary>
        public static string SuccesEmailRegistratieBedrijfVerzonden {
            get {
                return ResourceManager.GetString("SuccesEmailRegistratieBedrijfVerzonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters voor academiejaar {0} succesvol opgeslagen..
        /// </summary>
        public static string SuccesParametersAcademiejaar {
            get {
                return ResourceManager.GetString("SuccesParametersAcademiejaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht &apos;{0}&apos; succesvol aan {1} toegewezen..
        /// </summary>
        public static string SuccesStageAanStudentToegewezen {
            get {
                return ResourceManager.GetString("SuccesStageAanStudentToegewezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht &apos;{0}&apos; afgekeurd..
        /// </summary>
        public static string SuccesStageAfgekeurd {
            get {
                return ResourceManager.GetString("SuccesStageAfgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleider {0} succesvol gekoppeld aan stage {1}..
        /// </summary>
        public static string SuccesStagebegeleidingAanvraagGoedgekeurd {
            get {
                return ResourceManager.GetString("SuccesStagebegeleidingAanvraagGoedgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvraag stagebegeleiding afgekeurd..
        /// </summary>
        public static string SuccesStagebegeleidingAfgekeurd {
            get {
                return ResourceManager.GetString("SuccesStagebegeleidingAfgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvraag stagebegeleiding afgekeurd. Begeleider {0} losgekoppeld van stage &apos;{1}&apos;..
        /// </summary>
        public static string SuccesStagebegeleidingAfgekeurdBegeleiderLosgekoppeld {
            get {
                return ResourceManager.GetString("SuccesStagebegeleidingAfgekeurdBegeleiderLosgekoppeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagedossier voor stageopdracht  &apos;{0}&apos; aangeduid als ingediend..
        /// </summary>
        public static string SuccesStagedossierAangeduidAlsIngediend {
            get {
                return ResourceManager.GetString("SuccesStagedossierAangeduidAlsIngediend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagedossier van {0} afgekeurd..
        /// </summary>
        public static string SuccesStagedossierAfgekeurd {
            get {
                return ResourceManager.GetString("SuccesStagedossierAfgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagedossier van {0} goedgekeurd..
        /// </summary>
        public static string SuccesStagedossierGoedgekeurd {
            get {
                return ResourceManager.GetString("SuccesStagedossierGoedgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht &apos;{0}&apos; goedgekeurd..
        /// </summary>
        public static string SuccesStageGoedgekeurd {
            get {
                return ResourceManager.GetString("SuccesStageGoedgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student &apos;{0}&apos; succesvol aangemaakt..
        /// </summary>
        public static string SuccesStudentCreate {
            get {
                return ResourceManager.GetString("SuccesStudentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht &apos;{0}&apos; succesvol verwijderd..
        /// </summary>
        public static string SuccesVerwijderStageopdracht {
            get {
                return ResourceManager.GetString("SuccesVerwijderStageopdracht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht &apos;{0}&apos; uit mijn voorkeurstages verwijderd..
        /// </summary>
        public static string SuccesVoorkeurStageVerwijderen {
            get {
                return ResourceManager.GetString("SuccesVoorkeurStageVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stageopdracht &apos;{0}&apos; toegevoegd als voorkeur..
        /// </summary>
        public static string succesVoorkeurToevoegen {
            get {
                return ResourceManager.GetString("succesVoorkeurToevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvragen stagebegeleiding.
        /// </summary>
        public static string TitelAanvragenStagebegeleiding {
            get {
                return ResourceManager.GetString("TitelAanvragenStagebegeleiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratie rechten.
        /// </summary>
        public static string TitelAdminIndex {
            get {
                return ResourceManager.GetString("TitelAdminIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin verwijderen.
        /// </summary>
        public static string TitelAdminVerwijderen {
            get {
                return ResourceManager.GetString("TitelAdminVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afgekeurde stageopdrachten.
        /// </summary>
        public static string TitelAfgekeurdeStageopdrachten {
            get {
                return ResourceManager.GetString("TitelAfgekeurdeStageopdrachten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht stagevoorstellen.
        /// </summary>
        public static string TitelBedrijfStageVoorstellen {
            get {
                return ResourceManager.GetString("TitelBedrijfStageVoorstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht bedrijven.
        /// </summary>
        public static string TitelBedrijvenIndex {
            get {
                return ResourceManager.GetString("TitelBedrijvenIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschikbare stageopdrachten.
        /// </summary>
        public static string TitelBeschikbareStageopdrachten {
            get {
                return ResourceManager.GetString("TitelBeschikbareStageopdrachten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht contactpersonen.
        /// </summary>
        public static string TitelContactpersoonIndex {
            get {
                return ResourceManager.GetString("TitelContactpersoonIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goedgekeurde stageopdrachten.
        /// </summary>
        public static string TitelGoedgekeurdeStageopdrachten {
            get {
                return ResourceManager.GetString("TitelGoedgekeurdeStageopdrachten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string TitelLogin {
            get {
                return ResourceManager.GetString("TitelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn stagebegeleiding aanvragen.
        /// </summary>
        public static string TitelMijnAanvragenStagebegeleiding {
            get {
                return ResourceManager.GetString("TitelMijnAanvragenStagebegeleiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn stageopdrachten.
        /// </summary>
        public static string TitelMijnStageopdrachten {
            get {
                return ResourceManager.GetString("TitelMijnStageopdrachten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn stages.
        /// </summary>
        public static string TitelMijnStages {
            get {
                return ResourceManager.GetString("TitelMijnStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn voorkeurstages.
        /// </summary>
        public static string TitelMijnVoorkeurStages {
            get {
                return ResourceManager.GetString("TitelMijnVoorkeurStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw bedrijf.
        /// </summary>
        public static string TitelNieuwBedrijf {
            get {
                return ResourceManager.GetString("TitelNieuwBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw contactpersoon.
        /// </summary>
        public static string TitelNieuwContactpersoon {
            get {
                return ResourceManager.GetString("TitelNieuwContactpersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters nieuw academiejaar.
        /// </summary>
        public static string TitelNieuweAcademiejaarParameters {
            get {
                return ResourceManager.GetString("TitelNieuweAcademiejaarParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe begeleider.
        /// </summary>
        public static string TitelNieuweBegeleider {
            get {
                return ResourceManager.GetString("TitelNieuweBegeleider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe stageopdracht.
        /// </summary>
        public static string TitelNieuweStageopdracht {
            get {
                return ResourceManager.GetString("TitelNieuweStageopdracht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe student.
        /// </summary>
        public static string TitelNieuweStudent {
            get {
                return ResourceManager.GetString("TitelNieuweStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht gebruikers.
        /// </summary>
        public static string TitelOverzichtAppUsers {
            get {
                return ResourceManager.GetString("TitelOverzichtAppUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht parameters academiejaren.
        /// </summary>
        public static string TitelOverzichtParametersAcademiejaren {
            get {
                return ResourceManager.GetString("TitelOverzichtParametersAcademiejaren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht stages.
        /// </summary>
        public static string TitelOverzichtStages {
            get {
                return ResourceManager.GetString("TitelOverzichtStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters academiejaar.
        /// </summary>
        public static string TitelParametersAcademiejaar {
            get {
                return ResourceManager.GetString("TitelParametersAcademiejaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagecontracten genereren.
        /// </summary>
        public static string TitelStagecontracten {
            get {
                return ResourceManager.GetString("TitelStagecontracten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagedossieren goedkeuren.
        /// </summary>
        public static string TitelStagedossierenGoedkeuren {
            get {
                return ResourceManager.GetString("TitelStagedossierenGoedkeuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijst stages naar excel exporteren.
        /// </summary>
        public static string TitelStageNaarExcel {
            get {
                return ResourceManager.GetString("TitelStageNaarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht stageopdrachten van {0}.
        /// </summary>
        public static string TitelStageopdrachtenVanBedrijf {
            get {
                return ResourceManager.GetString("TitelStageopdrachtenVanBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht stageopdracht.
        /// </summary>
        public static string TitelStageopdrachtIndex {
            get {
                return ResourceManager.GetString("TitelStageopdrachtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijst stageopdracht naar excel exporteren.
        /// </summary>
        public static string TitelStageopdrachtNaarExcel {
            get {
                return ResourceManager.GetString("TitelStageopdrachtNaarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages toewijzen.
        /// </summary>
        public static string TitelStagesToewijzen {
            get {
                return ResourceManager.GetString("TitelStagesToewijzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegewezen stageopdrachten.
        /// </summary>
        public static string TitelToegewezenStageopdrachten {
            get {
                return ResourceManager.GetString("TitelToegewezenStageopdrachten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegewezen stageopdrachten zonder begeleider.
        /// </summary>
        public static string TitelToegewezenStageopdrachtenZonderBegeleider {
            get {
                return ResourceManager.GetString("TitelToegewezenStageopdrachtenZonderBegeleider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegewezen stages.
        /// </summary>
        public static string TitelToegewezenStages {
            get {
                return ResourceManager.GetString("TitelToegewezenStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset wachtwoord.
        /// </summary>
        public static string TitelWachtwoordResetten {
            get {
                return ResourceManager.GetString("TitelWachtwoordResetten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten?.
        /// </summary>
        public static string TitelWachtwoordVergeten {
            get {
                return ResourceManager.GetString("TitelWachtwoordVergeten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens mogen aangepast worden tot: {0}.
        /// </summary>
        public static string WarningBedrijfMagStageWijzigenTot {
            get {
                return ResourceManager.GetString("WarningBedrijfMagStageWijzigenTot", resourceCulture);
            }
        }
    }
}
