//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageBeheersTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StageBeheersTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin/einde stageperiode semester 1.
        /// </summary>
        public static string DisplayBeginEindeSemester1 {
            get {
                return ResourceManager.GetString("DisplayBeginEindeSemester1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin/einde stageperiode semester 2.
        /// </summary>
        public static string DisplayBeginEindeSemester2 {
            get {
                return ResourceManager.GetString("DisplayBeginEindeSemester2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Semester 1.
        /// </summary>
        public static string DisplayBeginSem1 {
            get {
                return ResourceManager.GetString("DisplayBeginSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Semester2.
        /// </summary>
        public static string DisplayBeginSem2 {
            get {
                return ResourceManager.GetString("DisplayBeginSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline voor bedrijven om stageopdrachten te wijzigen.
        /// </summary>
        public static string DisplayDeadlineBedrijfMagStageWijzigen {
            get {
                return ResourceManager.GetString("DisplayDeadlineBedrijfMagStageWijzigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einde Semester 1.
        /// </summary>
        public static string DisplayEindeSem1 {
            get {
                return ResourceManager.GetString("DisplayEindeSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einde Semester 2.
        /// </summary>
        public static string DisplayEindeSem2 {
            get {
                return ResourceManager.GetString("DisplayEindeSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord.
        /// </summary>
        public static string DisplayNewPassword {
            get {
                return ResourceManager.GetString("DisplayNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord bevestigen.
        /// </summary>
        public static string DisplayNieuwWachtwoordBevestigen {
            get {
                return ResourceManager.GetString("DisplayNieuwWachtwoordBevestigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidig wachtwoord.
        /// </summary>
        public static string DisplayOldPassword {
            get {
                return ResourceManager.GetString("DisplayOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string DisplayWachtwoord {
            get {
                return ResourceManager.GetString("DisplayWachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Account aangemaakt: &lt;/strong&gt;&lt;ul&gt;&lt;li&gt;Login: {0}&lt;/li&gt;&lt;li&gt;Wachtwoord: {1}&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string EmailRegistratieBedrijf {
            get {
                return ResourceManager.GetString("EmailRegistratieBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academiejaar mag niet tot het verleden behoren.
        /// </summary>
        public static string ErrorAcademiejaarInVerleden {
            get {
                return ResourceManager.GetString("ErrorAcademiejaarInVerleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het veld bedrijf is verplicht..
        /// </summary>
        public static string ErrorBedrijfVerplicht {
            get {
                return ResourceManager.GetString("ErrorBedrijfVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleider {0} bestaat reeds..
        /// </summary>
        public static string ErrorBegeleiderCreateHogentEmailBestaatAl {
            get {
                return ResourceManager.GetString("ErrorBegeleiderCreateHogentEmailBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen mislukt. Stagebegeleider is aan 1 of meerdere stages koppeld..
        /// </summary>
        public static string ErrorBegeleiderDeleteFailed {
            get {
                return ResourceManager.GetString("ErrorBegeleiderDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het nieuwe wachtwoord en het bevestigde antwoord komen niet overeen..
        /// </summary>
        public static string ErrorNieuwEnBevestigdWachtwoord {
            get {
                return ResourceManager.GetString("ErrorNieuwEnBevestigdWachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig Academiejaar formaat. beginjaar-eindjaar.
        /// </summary>
        public static string ErrorOngeldigAcademiejaarFormaat {
            get {
                return ResourceManager.GetString("ErrorOngeldigAcademiejaarFormaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige afbeelding grootte, max. {0} Kb..
        /// </summary>
        public static string ErrorOngeldigeAfbeeldingGrootte {
            get {
                return ResourceManager.GetString("ErrorOngeldigeAfbeeldingGrootte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het ingevoerde e-mailadres of wachtwoord is onjuist..
        /// </summary>
        public static string ErrorOngeldigeLoginPoging {
            get {
                return ResourceManager.GetString("ErrorOngeldigeLoginPoging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verplicht oud wachtwoord in te vullen..
        /// </summary>
        public static string ErrorOudWachtwoordVerplicht {
            get {
                return ResourceManager.GetString("ErrorOudWachtwoordVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleiding aanvraag goedkeuren mislukt: Stage &apos;{0}&apos; heeft al een stagebegeleider({1}).
        /// </summary>
        public static string ErrorStagebegeleidingAanvraagGoedgekeurd {
            get {
                return ResourceManager.GetString("ErrorStagebegeleidingAanvraagGoedgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foute stageperiode voor semester 1: begindatum moet na de einddatum liggen.
        /// </summary>
        public static string ErrorStageperiodeSem1 {
            get {
                return ResourceManager.GetString("ErrorStageperiodeSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foute stageperiode voor semester 2: begindatum moet na de einddatum liggen.
        /// </summary>
        public static string ErrorStageperiodeSem2 {
            get {
                return ResourceManager.GetString("ErrorStageperiodeSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student {0} bestaat reeds..
        /// </summary>
        public static string ErrorStudentCreateHogentEmailBestaatAl {
            get {
                return ResourceManager.GetString("ErrorStudentCreateHogentEmailBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link om wachtwoord te resetten is naar uw e-mail verzonden..
        /// </summary>
        public static string InfoResetWachtwoordVerzonden {
            get {
                return ResourceManager.GetString("InfoResetWachtwoordVerzonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens succesvol opgeslagen..
        /// </summary>
        public static string SuccesAdminsGewijzigd {
            get {
                return ResourceManager.GetString("SuccesAdminsGewijzigd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin {0} succesvol verwijderd..
        /// </summary>
        public static string SuccesAdminVerwijderd {
            get {
                return ResourceManager.GetString("SuccesAdminVerwijderd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleider {0} toegevoegd..
        /// </summary>
        public static string SuccesBegeleiderCreate {
            get {
                return ResourceManager.GetString("SuccesBegeleiderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registratie e-mail verzonden..
        /// </summary>
        public static string SuccesEmailRegistratieBedrijfVerzonden {
            get {
                return ResourceManager.GetString("SuccesEmailRegistratieBedrijfVerzonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters voor academiejaar {0} succesvol opgeslagen..
        /// </summary>
        public static string SuccesParametersAcademiejaar {
            get {
                return ResourceManager.GetString("SuccesParametersAcademiejaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begeleider {0} succesvol gekoppeld aan stage {1}..
        /// </summary>
        public static string SuccesStagebegeleidingAanvraagGoedgekeurd {
            get {
                return ResourceManager.GetString("SuccesStagebegeleidingAanvraagGoedgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvraag stagebegeleiding afgekeurd..
        /// </summary>
        public static string SuccesStagebegeleidingAfgekeurd {
            get {
                return ResourceManager.GetString("SuccesStagebegeleidingAfgekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvraag stagebegeleiding afgekeurd. Begeleider {0} losgekoppeld van stage &apos;{1}&apos;..
        /// </summary>
        public static string SuccesStagebegeleidingAfgekeurdBegeleiderLosgekoppeld {
            get {
                return ResourceManager.GetString("SuccesStagebegeleidingAfgekeurdBegeleiderLosgekoppeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student {0} toegevoegd..
        /// </summary>
        public static string SuccesStudentCreate {
            get {
                return ResourceManager.GetString("SuccesStudentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvragen stagebegeleiding.
        /// </summary>
        public static string TitelAanvragenStagebegeleidingIndex {
            get {
                return ResourceManager.GetString("TitelAanvragenStagebegeleidingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratie rechten.
        /// </summary>
        public static string TitelAdminIndex {
            get {
                return ResourceManager.GetString("TitelAdminIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin verwijderen.
        /// </summary>
        public static string TitelAdminVerwijderen {
            get {
                return ResourceManager.GetString("TitelAdminVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht bedrijven.
        /// </summary>
        public static string TitelBedrijvenIndex {
            get {
                return ResourceManager.GetString("TitelBedrijvenIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht contactpersonen.
        /// </summary>
        public static string TitelContactpersoonIndex {
            get {
                return ResourceManager.GetString("TitelContactpersoonIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string TitelLogin {
            get {
                return ResourceManager.GetString("TitelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw bedrijf.
        /// </summary>
        public static string TitelNieuwBedrijf {
            get {
                return ResourceManager.GetString("TitelNieuwBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw contactpersoon.
        /// </summary>
        public static string TitelNieuwContactpersoon {
            get {
                return ResourceManager.GetString("TitelNieuwContactpersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters nieuw academiejaar.
        /// </summary>
        public static string TitelNieuweAcademiejaarParameters {
            get {
                return ResourceManager.GetString("TitelNieuweAcademiejaarParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe begeleider.
        /// </summary>
        public static string TitelNieuweBegeleider {
            get {
                return ResourceManager.GetString("TitelNieuweBegeleider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe stageopdracht.
        /// </summary>
        public static string TitelNieuweStageopdracht {
            get {
                return ResourceManager.GetString("TitelNieuweStageopdracht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe student.
        /// </summary>
        public static string TitelNieuweStudent {
            get {
                return ResourceManager.GetString("TitelNieuweStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht parameters academiejaren.
        /// </summary>
        public static string TitelOverzichtParametersAcademiejaren {
            get {
                return ResourceManager.GetString("TitelOverzichtParametersAcademiejaren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters academiejaar.
        /// </summary>
        public static string TitelParametersAcademiejaar {
            get {
                return ResourceManager.GetString("TitelParametersAcademiejaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht stageopdracht.
        /// </summary>
        public static string TitelStageopdrachtIndex {
            get {
                return ResourceManager.GetString("TitelStageopdrachtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset wachtwoord.
        /// </summary>
        public static string TitelWachtwoordResetten {
            get {
                return ResourceManager.GetString("TitelWachtwoordResetten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten?.
        /// </summary>
        public static string TitelWachtwoordVergeten {
            get {
                return ResourceManager.GetString("TitelWachtwoordVergeten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens mogen aangepast worden tot: {0}.
        /// </summary>
        public static string WarningBedrijfMagStageWijzigenTot {
            get {
                return ResourceManager.GetString("WarningBedrijfMagStageWijzigenTot", resourceCulture);
            }
        }
    }
}
